--
-- PostgreSQL database dump
--

\restrict NihoeALNyOgnlx4T5a1lgE2Ywy6LlhHbeLdkKaeEN6T7uiphuYZ4iTMuXTxnBF0

-- Dumped from database version 15.15 (Debian 15.15-1.pgdg13+1)
-- Dumped by pg_dump version 15.15 (Debian 15.15-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: doctrine_migration_versions; Type: TABLE; Schema: public; Owner: symfony
--

CREATE TABLE public.doctrine_migration_versions (
    version character varying(191) NOT NULL,
    executed_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    execution_time integer
);


ALTER TABLE public.doctrine_migration_versions OWNER TO symfony;

--
-- Name: events; Type: TABLE; Schema: public; Owner: symfony
--

CREATE TABLE public.events (
    id integer NOT NULL,
    type_id integer NOT NULL,
    description text NOT NULL,
    place character varying(100) NOT NULL,
    date timestamp(0) without time zone NOT NULL,
    author_id integer NOT NULL,
    updated_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone
);


ALTER TABLE public.events OWNER TO symfony;

--
-- Name: events_id_seq; Type: SEQUENCE; Schema: public; Owner: symfony
--

ALTER TABLE public.events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user; Type: TABLE; Schema: public; Owner: symfony
--

CREATE TABLE public."user" (
    id integer NOT NULL,
    email character varying(180) NOT NULL,
    login character varying(20) NOT NULL,
    password character varying(255) NOT NULL,
    roles json NOT NULL
);


ALTER TABLE public."user" OWNER TO symfony;

--
-- Name: user_id_seq; Type: SEQUENCE; Schema: public; Owner: symfony
--

ALTER TABLE public."user" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: doctrine_migration_versions; Type: TABLE DATA; Schema: public; Owner: symfony
--

COPY public.doctrine_migration_versions (version, executed_at, execution_time) FROM stdin;
DoctrineMigrations\\Version20251201113415	2025-12-01 11:34:42	118
DoctrineMigrations\\Version20251204164141	2025-12-04 16:44:13	88
DoctrineMigrations\\Version20251204175623	2025-12-04 17:56:41	64
DoctrineMigrations\\Version20251204193223	2025-12-04 19:32:40	96
DoctrineMigrations\\Version20251204193901	2025-12-04 19:39:11	62
DoctrineMigrations\\Version20251216103728	2025-12-16 10:38:15	67
\.


--
-- Data for Name: events; Type: TABLE DATA; Schema: public; Owner: symfony
--

COPY public.events (id, type_id, description, place, date, author_id, updated_at) FROM stdin;
34	5	qwertyu123	qwertyu	2025-12-06 22:30:00	2	2025-12-16 10:39:21
35	1	asddd	asdasd123	2025-12-16 10:41:00	2	2025-12-16 11:51:56
36	1	testowy test	testowy test	2025-12-18 15:54:00	2	2025-12-16 11:54:43
37	1	123456	79843561	2025-12-16 12:35:00	2	2025-12-16 12:35:45
21	1	Awaria serwera produkcyjnego	Serwerownia HQ	2024-11-01 09:20:00	1	2025-12-16 11:51:56
22	2	Nieudana próba logowania	Panel Admina	2024-11-02 11:45:00	2	2025-12-16 11:51:56
23	3	Zmiana adresu klienta	CRM	2024-11-03 14:32:00	3	2025-12-16 11:51:56
24	4	Nowy użytkownik zarejestrowany	Portal	2024-11-04 08:10:00	1	2025-12-16 11:51:56
25	5	Usunięto raport miesięczny	Panel Raportów	2024-11-04 16:05:00	1	2025-12-16 11:51:56
26	6	Zaktualizowano wersję aplikacji	Backend	2024-11-05 21:30:00	1	2025-12-16 11:51:56
28	2	Backup bazy danych wykonany pomyślnie	Serwer DB	2024-11-06 01:00:00	3	2025-12-16 11:51:56
29	3	Nieznany wyjątek w module płatności	System płatności	2024-11-07 12:55:00	1	2025-12-16 11:51:56
31	1	Zdarzenie 1	ABCDE	2025-12-06 21:55:00	2	2025-12-16 11:51:56
32	1	Zdarzenie 1	ABCDE	2025-12-06 21:55:00	2	2025-12-16 11:51:56
27	2	Wysokie zużycie pamięci RAM	Serwer #2	2024-11-06 03:12:00	2	2025-12-16 11:51:56
30	5	Administrator zalogował się poprawnie	Panel Admina	2024-11-08 09:00:00	1	2025-12-16 11:51:56
33	1	1234567890\r\n1234567890\r\n1234567890\r\n1234567890\r\n1234567890\r\n1234567890\r\n1234567890\r\n1234567890\r\n1234567890\r\n1234567890\r\n1234567890\r\n1234567890	1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890	2025-12-12 01:03:00	2	2025-12-16 11:51:56
\.


--
-- Data for Name: user; Type: TABLE DATA; Schema: public; Owner: symfony
--

COPY public."user" (id, email, login, password, roles) FROM stdin;
1	admin@poczta.pl	admin	$2b$10$rRyF2OVj2N.L8lFSA8PGneNQFrCB7w3drdMBBfU3SGHr09dx76LxO	["ROLE_ADMIN"]
2	user1@poczta.pl	user1	$2b$10$rRyF2OVj2N.L8lFSA8PGneNQFrCB7w3drdMBBfU3SGHr09dx76LxO	["ROLE_USER"]
3	user2@poczta.pl	user2	$2b$10$rRyF2OVj2N.L8lFSA8PGneNQFrCB7w3drdMBBfU3SGHr09dx76LxO	["ROLE_USER"]
4	user3@poczta.pl	user3	$2b$10$rRyF2OVj2N.L8lFSA8PGneNQFrCB7w3drdMBBfU3SGHr09dx76LxO	["ROLE_USER"]
\.


--
-- Name: events_id_seq; Type: SEQUENCE SET; Schema: public; Owner: symfony
--

SELECT pg_catalog.setval('public.events_id_seq', 37, true);


--
-- Name: user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: symfony
--

SELECT pg_catalog.setval('public.user_id_seq', 4, true);


--
-- Name: doctrine_migration_versions doctrine_migration_versions_pkey; Type: CONSTRAINT; Schema: public; Owner: symfony
--

ALTER TABLE ONLY public.doctrine_migration_versions
    ADD CONSTRAINT doctrine_migration_versions_pkey PRIMARY KEY (version);


--
-- Name: events events_pkey; Type: CONSTRAINT; Schema: public; Owner: symfony
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT events_pkey PRIMARY KEY (id);


--
-- Name: user user_pkey; Type: CONSTRAINT; Schema: public; Owner: symfony
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_pkey PRIMARY KEY (id);


--
-- Name: uniq_8d93d649e7927c74; Type: INDEX; Schema: public; Owner: symfony
--

CREATE UNIQUE INDEX uniq_8d93d649e7927c74 ON public."user" USING btree (email);


--
-- PostgreSQL database dump complete
--

\unrestrict NihoeALNyOgnlx4T5a1lgE2Ywy6LlhHbeLdkKaeEN6T7uiphuYZ4iTMuXTxnBF0

